### PR TITLE
Neo4j version 5 patch

### PR DESCRIPTION
**Pull request by mbaric758**
Added class for detecting Neo4j version and adapted _driver.py module to use version 5 specific syntax if version 5 is detected.

### CODE REVIEW

**Comment by deeenes** [comment]
Hi @mbaric758,

Thank you, very helpful!

I'll merge it right away, only some minor coding style points:

- Use pascal case for the class name (without underscores), it could be `Neo4jVersion`
- Would be nice if the main class carried the version since initialization (or connection) in an attr or property
- Would it be sleeker to have `version` instead of `get_version()`
- Give a shorter name for the module, e.g. `_n4jversion`
- Use `import` instead of `from ...`

And the most important: have you tested it also with 4.x, or only with 5.x?

**Comment by mbaric758** [comment]
> Hi @mbaric758,
> 
> Thank you, very helpful!
> 
> I'll merge it right away, only some minor coding style points:
> 
>     * Use pascal case for the class name (without underscores), it could be `Neo4jVersion`
> 
>     * Would be nice if the main class carried the version since initialization (or connection) in an attr or property
> 
>     * Would it be sleeker to have `version` instead of `get_version()`
> 
>     * Give a shorter name for the module, e.g. `_n4jversion`
> 
>     * Use `import` instead of `from ...`
> 
> 
> And the most important: have you tested it also with 4.x, or only with 5.x?

Hi @deeenes  , 

Thanks, I'll be sure to fix the styling!

The tests with neo4j v5 are good. I ran the biocypher tests on neo4j community edition 4.4.30 and I seem to be getting: 

`ERROR    neo4ju:_driver.py:1061 Failed to run query: CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid input '.': expected "IF" or <EOF> (line 1, column 35 (offset: 34))
"DROP CONSTRAINT ClinicallyRelevant.sequenceVariant_id IF EXISTS"
                                   ^}
`

I also reran the tests on a clean biocypeher clone with neo4j community edition 4.4.30 and the `DROP` syntax problem seems to be present even in the clean clone.

`ERROR    neo4ju:_driver.py:983 Failed to run query: CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid input '.': expected "IF" or <EOF> (line 1, column 30 (offset: 29))
"DROP INDEX ClinicallyRelevant.sequenceVariant_id"
                              ^}`
`ERROR    neo4ju:_driver.py:983 Failed to run query: CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid input '.': expected "IF" or <EOF> (line 1, column 35 (offset: 34))
"DROP CONSTRAINT ClinicallyRelevant.sequenceVariant_id"
                                   ^}`.

**Comment by deeenes** [comment]
Hi @mbaric758, We should find out what's the problem with that query, where is the log message [from this line](https://github.com/saezlab/neo4j-utils/blob/7719e591b4cc70793969ccda596bb0a02cfe47b2/neo4j_utils/_driver.py#L627)? The reason can be either here or in biocypher.

**Comment by slobentanzer** [comment]
Hi @mbaric758, @deeenes,
this is related to the fact that identifiers with `.` need to be escaped in Cypher queries. There are no Cypher queries formulated in BioCypher, directly, `neo4j_utils` does that. The way to fix it is to escape the identifier in question, i.e., it should be:

```
DROP CONSTRAINT `ClinicallyRelevant.sequenceVariant_id` IF EXISTS
```

**Comment by deeenes** [comment]
@mbaric758 Then I'll merge this PR after your updates
Let me know if you want to address the other issue in another PR

**Comment by mbaric758** [comment]
Hi @deeenes ,

I modified the PR according to your suggestions, and escaped the query names in the `DROP` syntax as @slobentanzer suggested, so the errors I wrote about in https://github.com/saezlab/neo4j-utils/pull/5#issuecomment-1983152398 are fixed for both versions (neo4j community 4.4.30 and v5).

**Comment by deeenes** [comment]
Hi @mbaric758 , this looks all good for now, thanks a lot for the contribution!

**Pull request merged**
